//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant
    {
        public int id { get; set; }
        public string NamaLengkap { get; set; }
        public string Email { get; set; }
        public string Handphone { get; set; }
        public bool WillAttend { get; set; }
        public int MasterEventId { get; set; }
    
        public virtual MasterEvent MasterEvent { get; set; }
    }
}
